# ========================================
#
# [ams-ingest-dataflow] props :: log
#
# ========================================

# ALL > TRACE > DEBUG > INFO > WARN > ERROR > OFF
logging:

  group:
    app: com.packt.example
    spring: org.springframework
    spring-web: org.springframework.web
    spring-security: org.springframework.security

  level:
    app: debug
    spring: info
    spring-web: info
    spring-security: debug
