server:
  port: 8302
  servlet:
    session:
      persistent: on

spring:

  profiles:
    active: ${PROFILE:local}
    include: log

  thymeleaf.cache: false

  datasource:
    url: jdbc:mysql://1.217.118.166:3306/oauth
    username: dandi
    password: dandi12#$
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MariaDBDialect
      hbm2ddl.auto: validate

## [ logging ]
logging.config: classpath:logback-spring.xml